[package]
name = "p2p-chat"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol.workspace = true

anyhow.workspace = true
